// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msg.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//消息类别
type MsgType int32

const (
	MsgType_C2C     MsgType = 0
	MsgType_C2G     MsgType = 1
	MsgType_C2S     MsgType = 2
	MsgType_S2C     MsgType = 3
	MsgType_PUSH    MsgType = 4
	MsgType_PULL    MsgType = 5
	MsgType_LOGIN   MsgType = 6
	MsgType_LOGOUT  MsgType = 7
	MsgType_KICKOUT MsgType = 8
)

var MsgType_name = map[int32]string{
	0: "C2C",
	1: "C2G",
	2: "C2S",
	3: "S2C",
	4: "PUSH",
	5: "PULL",
	6: "LOGIN",
	7: "LOGOUT",
	8: "KICKOUT",
}

var MsgType_value = map[string]int32{
	"C2C":     0,
	"C2G":     1,
	"C2S":     2,
	"S2C":     3,
	"PUSH":    4,
	"PULL":    5,
	"LOGIN":   6,
	"LOGOUT":  7,
	"KICKOUT": 8,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_85aa4552279d3b4a, []int{0}
}

type Msg struct {
	MsgId                string   `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Seq                  int32    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Type                 MsgType  `protobuf:"varint,3,opt,name=type,proto3,enum=im.MsgType" json:"type,omitempty"`
	Content              []byte   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_85aa4552279d3b4a, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *Msg) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Msg) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_C2C
}

func (m *Msg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type MsgAck struct {
	MsgId                string   `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAck) Reset()         { *m = MsgAck{} }
func (m *MsgAck) String() string { return proto.CompactTextString(m) }
func (*MsgAck) ProtoMessage()    {}
func (*MsgAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_85aa4552279d3b4a, []int{1}
}

func (m *MsgAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAck.Unmarshal(m, b)
}
func (m *MsgAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAck.Marshal(b, m, deterministic)
}
func (m *MsgAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAck.Merge(m, src)
}
func (m *MsgAck) XXX_Size() int {
	return xxx_messageInfo_MsgAck.Size(m)
}
func (m *MsgAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAck proto.InternalMessageInfo

func (m *MsgAck) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

type LoginContent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginContent) Reset()         { *m = LoginContent{} }
func (m *LoginContent) String() string { return proto.CompactTextString(m) }
func (*LoginContent) ProtoMessage()    {}
func (*LoginContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_85aa4552279d3b4a, []int{2}
}

func (m *LoginContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginContent.Unmarshal(m, b)
}
func (m *LoginContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginContent.Marshal(b, m, deterministic)
}
func (m *LoginContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginContent.Merge(m, src)
}
func (m *LoginContent) XXX_Size() int {
	return xxx_messageInfo_LoginContent.Size(m)
}
func (m *LoginContent) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginContent.DiscardUnknown(m)
}

var xxx_messageInfo_LoginContent proto.InternalMessageInfo

func (m *LoginContent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginContent) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterEnum("im.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*Msg)(nil), "im.Msg")
	proto.RegisterType((*MsgAck)(nil), "im.MsgAck")
	proto.RegisterType((*LoginContent)(nil), "im.LoginContent")
}

func init() { proto.RegisterFile("proto/msg.proto", fileDescriptor_85aa4552279d3b4a) }

var fileDescriptor_85aa4552279d3b4a = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd0, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc0, 0x71, 0xb3, 0xfe, 0x7e, 0x1b, 0x1a, 0x1e, 0x1e, 0x8a, 0x07, 0x2d, 0x3d, 0x15, 0x0f,
	0x15, 0xea, 0x5d, 0x90, 0x1e, 0x6a, 0x59, 0x6b, 0xa5, 0xdd, 0xfe, 0x80, 0xb9, 0x85, 0x58, 0x24,
	0x4d, 0x5d, 0x0a, 0xb2, 0xff, 0x5e, 0x9a, 0x4c, 0x4f, 0xde, 0x3e, 0x5f, 0xf2, 0x20, 0x8f, 0x07,
	0x57, 0xe3, 0x51, 0x4e, 0xf2, 0x41, 0x28, 0x9e, 0x6a, 0xe1, 0xa2, 0x17, 0xf1, 0x07, 0x58, 0xb5,
	0xe2, 0x78, 0x0d, 0x8e, 0x50, 0xbc, 0x3c, 0x84, 0x24, 0x22, 0x49, 0xd0, 0x9a, 0x40, 0x0a, 0x96,
	0x62, 0x5f, 0xe1, 0x22, 0x22, 0x89, 0xd3, 0xce, 0xc4, 0x3b, 0xb0, 0xa7, 0xd3, 0xc8, 0x42, 0x2b,
	0x22, 0xc9, 0x65, 0xb6, 0x4c, 0x7b, 0x91, 0xd6, 0x8a, 0x6f, 0x4e, 0x23, 0x6b, 0xf5, 0x03, 0x86,
	0xe0, 0xed, 0xe5, 0x30, 0xb1, 0x61, 0x0a, 0xed, 0x88, 0x24, 0xab, 0xf6, 0x37, 0xe3, 0x5b, 0x70,
	0x6b, 0xc5, 0x9f, 0xf7, 0x9f, 0xff, 0x7f, 0x16, 0x3f, 0xc1, 0xaa, 0x92, 0xbc, 0x1f, 0x72, 0x33,
	0x8f, 0x08, 0xf6, 0xb0, 0x13, 0xec, 0x3c, 0xa4, 0x8d, 0x37, 0xe0, 0x8f, 0x3b, 0xa5, 0xbe, 0xe5,
	0xf1, 0xa0, 0xb7, 0x0a, 0xda, 0xbf, 0xbe, 0x67, 0xe0, 0x9d, 0x57, 0x41, 0x0f, 0xac, 0x3c, 0xcb,
	0xe9, 0x85, 0x41, 0x41, 0x89, 0x41, 0x47, 0x17, 0x33, 0xba, 0x2c, 0xa7, 0x16, 0xfa, 0x60, 0xbf,
	0x6d, 0xbb, 0x17, 0x6a, 0x1b, 0x55, 0x15, 0x75, 0x30, 0x00, 0xa7, 0x6a, 0x8a, 0xf2, 0x95, 0xba,
	0x08, 0xe0, 0x56, 0x4d, 0xd1, 0x6c, 0x37, 0xd4, 0xc3, 0x25, 0x78, 0xeb, 0x32, 0x5f, 0xcf, 0xe1,
	0xbf, 0xbb, 0xfa, 0x76, 0x8f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x4c, 0x31, 0x97, 0x4e,
	0x01, 0x00, 0x00,
}
